### ISSUE TITLE
Manual "Rabobank iDEAL Professional" outdated

### ISSUE THREAD

**Issue by remcotolsma** [wp-pay-gateways/ideal-advanced-v3#4]
The manual on https://www.pronamic.nl/support/pronamic-ideal-koppelen-met-rabobank-ideal-professional-v3/ is outdated.

> ### Privé sleutel en certificaat instellen
>
> 1. Ga naar het **iDEAL Dashboard** en kies **Profiel » Tabblad ‘Beveiliging’**;
> 2. upload het zojuist aangemaakte bestand `bestandsnaam.cer`;
> 3. open in het WordPress dashboard nu opnieuw de pagina van de aangemaakte iDEAL-configuratie. Als bovenaan op de pagina geen foutmeldingen door Pronamic iDEAL worden getoond, is het certificaat succesvol ingesteld.

@kjtolsma you were in the process of restructuring/merging the manual? Can i change https://www.pronamic.nl/support/pronamic-ideal-koppelen-met-rabobank-ideal-professional-v3/ or should this be done in another way?

We had a customer who accidentally uploaded the certificate on the "Rabo iDEAL Dashboard → Merchant data → General customer data" (Dutch: "Rabo iDEAL Dashboard → Acceptant beheer → Algemene klantgegevens") page.

**English:**
Rabo iDEAL Dashboard → Merchant data → iDEAL Service data

![ideal rabobank nl_msp_nl_modmerchantsubscription_idealsubscriptionfinder_fb9875d5115e41cce0a4d9cd8567603ca699770f4b1ed97271cc0c06e3babd8c=19d8ba110e462c48e0c719decc48ed7453974d8943d329ac948091baf2e89c4a(iPad Air)](https://user-images.githubusercontent.com/869674/178221139-ffb29f22-425e-4666-ad3e-19b517c6744e.png)

**Dutch:**
Rabo iDEAL Dashboard → Acceptant beheer → iDEAL Service data

![ideal rabobank nl_msp_nl_modmerchantsubscription_idealsubscriptionfinder_fb9875d5115e41cce0a4d9cd8567603ca699770f4b1ed97271cc0c06e3babd8c=19d8ba110e462c48e0c719decc48ed7453974d8943d329ac948091baf2e89c4a t_lb=t(iPad Air)](https://user-images.githubusercontent.com/869674/178221157-5ff88c29-17ce-43b4-b9b0-5e6b7c3828cf.png)

CC: @rvdsteege

**Comment by remcotolsma** [comment]
This is also stated in the Rabobank manual: "Rabobank → Handleiding → iDEAL Professional → Versie april 2019" (`Manual_iDEAL_MSP_ manual_2019-04.pdf`) on page 43:

> ### Certificaten bij aansluitmethode iDEAL Professional
>
> Bij iDEAL Professional dient u zelf te zorgen voor een certificaat voor de digitale handtekening in uw iDEAL betaalverzoeken. Dit certificaat heeft een maximale geldigheidsduur van 5 jaar. Hoe u dit certificaat kunt aanmaken kunt u lezen in de Merchant Integratiegids (zie module 3).
>
> Het isn belangrijk dat u de geldigheidsduur van uw certificaat bewaakt, zodat u kunt zorgen voor een tijdige vervanging. Indien u voorafgaand aan de verloopdatum van uw oude certificaat een nieuw certificaat in het iDEAL Dashboard toevoegt, voorkomt u dat transacties worden afgekeurd op het moment dat u het nieuwe certificaat in uw eigen webwinkel activeert.
>
> **Als u gebruik maakt van iDEAL Professional kunt u via Acceptant beheer> iDEAL Service gegevens onderaan “+ Certificaten” openklappen (bij andere aansluitmethodes ontbreekt onderaaan “+ Certificaten”). Via de knop “Nieuw Certificaat kunt u vervolgens de public key die bij uw signeercertificaat hoort uploaden. Met de knop ‘Bladeren’ selecteert u het juiste bestand (de naam van de public key eindigt in het algemeen op .cer of .crt. ). Na het uploaden van dit bestand kan de iDEAL acquirer/routing service controleren of je betaalverzoeken met het juiste certificaat ondertekend zijn.**

[Handleiding_iDEAL_MSP_handleiding_2019-04.pdf](https://github.com/pronamic/wp-pronamic-pay-ideal-advanced-v3/files/9082261/Handleiding_iDEAL_MSP_handleiding_2019-04.pdf)

**Comment by remcotolsma** [comment]
At the moment we do not know whether this is the same within the new ING iDEAL dashboard (https://ideal-portal.ing.nl/ | https://sandbox.ideal-portal.ing.nl/). In "ING → iDEAL Advanced → Integration manual PHP → English → June 2022" (`iDEAL_Advanced_PHP_EN_v2.5.9.pdf`) on page 11:

> 5. Upload `cert.cer` to the test environment of the iDEAL Acquiring platform (via the iDEAL Dashboard).

- [iDEAL_Advanced_PHP_EN_v2.5.9.pdf](https://github.com/pronamic/wp-pronamic-pay-ideal-advanced-v3/files/9082276/iDEAL_Advanced_PHP_EN_v2.5.9.pdf)
- [iDEAL Migration Manual Step by Step_tcm162-236314.pdf](https://github.com/pronamic/wp-pronamic-pay-ideal-advanced-v3/files/9082277/iDEAL.Migration.Manual.Step.by.Step_tcm162-236314.pdf)
- [iDEAL Migratie Handleiding Stap voor Stap_tcm162-235695.pdf](https://github.com/pronamic/wp-pronamic-pay-ideal-advanced-v3/files/9082278/iDEAL.Migratie.Handleiding.Stap.voor.Stap_tcm162-235695.pdf)

**Comment by kjtolsma** [comment]
I think it is best to do this directly on the "new" site: http://remcot1.sg-host.com/handleidingen/ing-ideal-advanced-v3/.

**Comment by rvdsteege** [comment]
In section 'iDEAL-configuratie verplicht testen':
> Doorloop de testbetalingen zoals vermeld in het kader Test;

Maybe we should list the test amounts, as these are not mentioned in the gateway settings anymore since a while?

**Comment by remcotolsma** [comment]
Updated the manual:
https://www.pronamicpay.com/nl/handleidingen/hoe-koppel-je-rabobank-ideal-professional-v3-aan-wordpress-met-pronamic-pay/

> ### Privé sleutel en certificaat instellen
> 
> - Ga in het **Rabo iDEAL Dashboard** via het menu “**Acceptant beheer**” naar het subitem “**iDEAL Service gegevens**”;
> - Onderaan “**+ Certificaten**” openklappen en via de knop “**Nieuw Certificaat**” het zojuist aangemaakte bestand `bestandsnaam.cer` toevoegen;
> - Open in het WordPress dashboard nu opnieuw de pagina van de aangemaakte iDEAL-configuratie. Als bovenaan op de pagina geen foutmeldingen door Pronamic Pay worden getoond, is het certificaat succesvol ingesteld.

---

> Maybe we should list the test amounts, as these are not mentioned in the gateway settings anymore since a while?

Added.

---

Auto translated English page:
https://www.pronamicpay.com/en/manuals/how-to-connect-rabobank-ideal-professional-v3-to-wordpress-with-pronamic-pay/
